// Generates apps-script/Schema.gs from src/lib/sheet-schema.ts + src/data/seed.ts
// Run: npm run gen:apps-script
import { writeFileSync } from "node:fs";
import { SETTINGS_FIELDS, SHEET_HEADERS } from "../src/lib/sheet-schema.ts";
import {
  seedBeforeAfter, seedCalendar, seedCampaigns, seedFactory, seedGallery, seedProjects, seedServices, seedSettings, seedTestimonials,
} from "../src/data/seed.ts";

const camel = (h: string) =>
  h.split(/[^A-Za-z0-9]+/).filter(Boolean).map((w, i) => (i ? w[0].toUpperCase() + w.slice(1).toLowerCase() : w.toLowerCase())).join("");

const cell = (v: unknown): string => {
  if (v === undefined || v === null) return "";
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (Array.isArray(v)) {
    if (v.length && typeof v[0] === "object") return (v as { q: string; a: string }[]).map((f) => `${f.q} :: ${f.a}`).join("\n");
    return v.join("\n");
  }
  return String(v);
};

const rows = (headers: readonly string[], items: object[]) =>
  items.map((it) => headers.map((h) => cell((it as Record<string, unknown>)[camel(h)])));

const settingsRows = SETTINGS_FIELDS.map(([label, key, note]) => {
  const v = (seedSettings as unknown as Record<string, unknown>)[key];
  return [label, Array.isArray(v) ? v.join(", ") : cell(v), note];
});

const seed = {
  SETTINGS: settingsRows,
  SERVICES: rows(SHEET_HEADERS.SERVICES, seedServices),
  PROJECTS: rows(SHEET_HEADERS.PROJECTS, seedProjects),
  GALLERY: rows(SHEET_HEADERS.GALLERY, seedGallery),
  BEFORE_AFTER: rows(SHEET_HEADERS.BEFORE_AFTER, seedBeforeAfter),
  TESTIMONIALS: rows(SHEET_HEADERS.TESTIMONIALS, seedTestimonials),
  FACTORY: rows(SHEET_HEADERS.FACTORY, seedFactory),
  CONTENT_CALENDAR: rows(SHEET_HEADERS.CONTENT_CALENDAR, seedCalendar),
  CAMPAIGNS: rows(SHEET_HEADERS.CAMPAIGNS, seedCampaigns),
};

const out = `// AUTO-GENERATED by scripts/gen-apps-script.ts — do not edit by hand.
// Sheet structure (headers) and first-run seed content.

var SCHEMA = ${JSON.stringify({ SETTINGS: ["Setting", "Value", "Notes"], ...SHEET_HEADERS }, null, 2)};

var SETTINGS_KEYS = ${JSON.stringify(Object.fromEntries(SETTINGS_FIELDS.map(([l, k]) => [l, k])), null, 2)};

var SEED = ${JSON.stringify(seed, null, 2)};
`;
writeFileSync(new URL("../apps-script/Schema.gs", import.meta.url), out);
console.log("apps-script/Schema.gs written");
