// AUTO-GENERATED by scripts/gen-apps-script.ts — do not edit by hand.
// Sheet structure (headers) and first-run seed content.

var SCHEMA = {
  "SETTINGS": [
    "Setting",
    "Value",
    "Notes"
  ],
  "SERVICES": [
    "Service ID",
    "Service Name",
    "Category",
    "Slug",
    "Short Description",
    "Full Description",
    "Main Image",
    "Gallery Images",
    "Starting Price",
    "SEO Title",
    "SEO Description",
    "H1",
    "Image Alt",
    "Benefits",
    "Materials",
    "Design Examples",
    "FAQs",
    "Featured",
    "Display Order",
    "WhatsApp Message",
    "Active"
  ],
  "PROJECTS": [
    "Project ID",
    "Project Name",
    "Slug",
    "Location",
    "Category",
    "Service Slug",
    "Description",
    "Project Date",
    "Area",
    "Budget Range",
    "Cover Image",
    "Gallery Images",
    "Featured",
    "Display Order",
    "Active"
  ],
  "GALLERY": [
    "Image ID",
    "Project ID",
    "Category",
    "Image URL",
    "Title",
    "Description",
    "Display Order",
    "Active"
  ],
  "BEFORE_AFTER": [
    "ID",
    "Project Name",
    "Description",
    "Location",
    "Category",
    "Before Image",
    "After Image",
    "Display Order",
    "Active"
  ],
  "TESTIMONIALS": [
    "Testimonial ID",
    "Customer Name",
    "Location",
    "Project Type",
    "Review",
    "Rating",
    "Photo",
    "Display Order",
    "Active"
  ],
  "FACTORY": [
    "ID",
    "Type",
    "Title",
    "Description",
    "Image URL",
    "Display Order",
    "Active"
  ],
  "LEADS": [
    "Lead ID",
    "Date",
    "Time",
    "Name",
    "Phone",
    "WhatsApp",
    "Email",
    "City",
    "Property Type",
    "Requirement",
    "Budget",
    "Property Status",
    "Preferred Contact",
    "Message",
    "File URL",
    "Source",
    "Campaign",
    "UTM Source",
    "UTM Medium",
    "UTM Campaign",
    "UTM Content",
    "Status",
    "Assigned To",
    "Follow Up Date",
    "Last Contact Date",
    "Remarks",
    "Created At",
    "Updated At",
    "Form Type",
    "Landing Page",
    "Referrer",
    "Submission ID"
  ],
  "EVENTS": [
    "Event ID",
    "Event Type",
    "Page",
    "Service",
    "Label",
    "Source",
    "Campaign",
    "UTM Source",
    "UTM Medium",
    "UTM Campaign",
    "UTM Content",
    "Date",
    "Time",
    "Created At"
  ],
  "SOCIAL_POSTS": [
    "Post ID",
    "Content Type",
    "Platform",
    "Caption",
    "Image URL",
    "Video URL",
    "Hashtags",
    "Campaign ID",
    "Scheduled Date",
    "Scheduled Time",
    "Status",
    "Published URL",
    "Error Message",
    "Created At",
    "Updated At",
    "Container ID"
  ],
  "CONTENT_CALENDAR": [
    "Day",
    "Category",
    "Service Slug",
    "Content Type",
    "Platform",
    "Time",
    "Active"
  ],
  "CAMPAIGNS": [
    "Campaign ID",
    "Campaign Name",
    "Platform",
    "Start Date",
    "End Date",
    "Landing Page",
    "UTM Source",
    "UTM Medium",
    "UTM Campaign",
    "UTM Content",
    "Leads",
    "WhatsApp Clicks",
    "Calls",
    "Conversions",
    "Status"
  ]
};

var SETTINGS_KEYS = {
  "Company Name": "companyName",
  "Logo URL": "logoUrl",
  "Phone": "phone",
  "WhatsApp Number": "whatsappNumber",
  "Email": "email",
  "Office Address": "officeAddress",
  "Factory Address": "factoryAddress",
  "Google Maps URL": "googleMapsUrl",
  "Factory Maps URL": "factoryMapsUrl",
  "Google Business Profile URL": "googleBusinessProfileUrl",
  "Google Review URL": "googleReviewUrl",
  "Instagram URL": "instagramUrl",
  "Instagram Handle": "instagramHandle",
  "Facebook URL": "facebookUrl",
  "YouTube URL": "youtubeUrl",
  "Working Hours": "workingHours",
  "WhatsApp Default Message": "whatsappDefaultMessage",
  "Footer Text": "footerText",
  "Primary CTA": "primaryCta",
  "Secondary CTA": "secondaryCta",
  "Default City": "defaultCity",
  "Service Areas": "serviceAreas",
  "Staff Members": "staffMembers",
  "Hero Image": "heroImage",
  "Factory Hero Image": "factoryHeroImage",
  "About Image": "aboutImage",
  "Years Experience": "yearsExperience",
  "Projects Completed": "projectsCompleted",
  "Factory Area": "factoryArea",
  "Auto Publish": "autoPublish"
};

var SEED = {
  "SETTINGS": [
    [
      "Company Name",
      "VBays Interiors",
      ""
    ],
    [
      "Logo URL",
      "",
      "Public image URL (PNG/SVG). Leave blank to use the text logo."
    ],
    [
      "Phone",
      "+91 90000 00000",
      "Shown on the site and used for click-to-call"
    ],
    [
      "WhatsApp Number",
      "919000000000",
      "Country code + number, digits only, e.g. 919876543210"
    ],
    [
      "Email",
      "hello@vbaysinteriors.com",
      ""
    ],
    [
      "Office Address",
      "Design Studio, Main Road, Visakhapatnam, Andhra Pradesh",
      ""
    ],
    [
      "Factory Address",
      "Modular Manufacturing Unit, Industrial Estate, Visakhapatnam, Andhra Pradesh",
      ""
    ],
    [
      "Google Maps URL",
      "",
      "Office directions link (optional)"
    ],
    [
      "Factory Maps URL",
      "",
      "Factory directions link (optional)"
    ],
    [
      "Google Business Profile URL",
      "",
      "Used for 'See Our Google Reviews'"
    ],
    [
      "Google Review URL",
      "",
      "Direct 'write a review' link"
    ],
    [
      "Instagram URL",
      "https://www.instagram.com/",
      ""
    ],
    [
      "Instagram Handle",
      "vbaysinteriors",
      "Without @"
    ],
    [
      "Facebook URL",
      "",
      ""
    ],
    [
      "YouTube URL",
      "",
      ""
    ],
    [
      "Working Hours",
      "Mon – Sat: 9:30 AM – 7:00 PM · Sunday by appointment",
      ""
    ],
    [
      "WhatsApp Default Message",
      "Hello, I am interested in your interior design services. I would like to discuss my project.",
      ""
    ],
    [
      "Footer Text",
      "Complete modular interiors — designed by our studio, manufactured in our own factory and installed by our team.",
      ""
    ],
    [
      "Primary CTA",
      "Get Free Consultation",
      ""
    ],
    [
      "Secondary CTA",
      "Chat on WhatsApp",
      ""
    ],
    [
      "Default City",
      "Visakhapatnam",
      "Replaces {city} in SEO fields"
    ],
    [
      "Service Areas",
      "Visakhapatnam, Vizianagaram, Anakapalli, Srikakulam, Rajahmundry",
      "Comma separated. Each gets local SEO pages."
    ],
    [
      "Staff Members",
      "Sales Team, Designer 1, Designer 2, Site Supervisor",
      "Comma separated. Used for lead assignment."
    ],
    [
      "Hero Image",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=75",
      "Home page hero image URL"
    ],
    [
      "Factory Hero Image",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1600&q=75",
      ""
    ],
    [
      "About Image",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=75",
      ""
    ],
    [
      "Years Experience",
      "",
      "Optional. Only shown if filled."
    ],
    [
      "Projects Completed",
      "",
      "Optional. Only shown if filled."
    ],
    [
      "Factory Area",
      "",
      "Optional, e.g. 20,000 sq.ft"
    ],
    [
      "Auto Publish",
      "FALSE",
      "TRUE = approved posts with a date/time publish automatically"
    ]
  ],
  "SERVICES": [
    [
      "SRV-001",
      "Full Home Interiors",
      "Full Home",
      "full-home-interiors",
      "One team for your entire home — planning, 3D design, factory-made modular furniture and installation.",
      "Our full home interiors bring every room together under a single design language. We plan the space, visualise it in 3D, manufacture modular units in our own factory and install everything with one coordinated schedule — so you deal with one team from first meeting to final handover.",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "",
      "Full Home Interiors in {city} | Design + Factory + Installation",
      "End-to-end full home interiors in {city}: space planning, 3D design, in-house modular manufacturing and installation by one team.",
      "Full Home Interiors in {city}",
      "Full home interior with modular furniture",
      "Single point of contact for the entire home\nConsistent design language across every room\nFactory-made modular units for precise fit and finish\nCoordinated manufacturing and installation schedule",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "2BHK apartment\n3BHK apartment\nIndependent villa\nRenovation of existing home",
      "What is included in full home interiors? :: Typically the kitchen, wardrobes, TV unit, pooja unit, storage, false ceiling coordination and loose furniture planning. The exact scope is finalised during consultation.\nDo you manufacture the furniture yourselves? :: Yes. Modular units are manufactured in our own factory, which lets us control quality and schedule.\nCan I do a few rooms first and the rest later? :: Yes. We can plan the complete home and execute in phases.",
      "TRUE",
      "1",
      "Hello, I am interested in Full Home Interiors. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-002",
      "Modular Kitchen",
      "Kitchen",
      "modular-kitchen",
      "L-shaped, U-shaped, parallel and island kitchens — made to measure in our factory.",
      "A modular kitchen should work as hard as you do. We design around your cooking habits, appliances and storage needs, then manufacture every carcass and shutter in our factory for a precise, durable fit.",
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=75",
      "",
      "Modular Kitchen in {city} | Factory-Made, Custom Designed",
      "Custom modular kitchens in {city} designed in 3D and manufactured in our own factory. L-shaped, U-shaped, parallel and island layouts.",
      "Modular Kitchen Designers in {city}",
      "Modern modular kitchen with handleless cabinets",
      "Ergonomic work-triangle planning\nMoisture-resistant materials for wet areas\nTall units, corner solutions & smart accessories\nPrecise factory manufacturing",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "L-shaped kitchen\nU-shaped kitchen\nParallel kitchen\nIsland kitchen\nStraight kitchen",
      "Which material is best for a modular kitchen? :: For carcasses we usually recommend BWP-grade plywood near the sink and water areas. Shutter finishes depend on budget and look — laminate, acrylic or PU.\nHow long does a modular kitchen take? :: After design approval, manufacturing and installation usually take a few weeks, depending on the finish and scope.",
      "TRUE",
      "2",
      "Hello, I am interested in Modular Kitchen Interior Design. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-003",
      "Bedroom Interiors",
      "Bedroom",
      "bedroom-interiors",
      "Calm, functional bedrooms with wardrobes, beds, side units and dressing areas.",
      "We design bedrooms that balance rest and storage — wardrobes, beds with storage, study corners and dressing units — all built to your room's exact measurements.",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "",
      "Bedroom Interiors in {city} | Wardrobes, Beds & Storage",
      "Bedroom interior design in {city} with factory-made wardrobes, storage beds and dressing units.",
      "Bedroom Interior Design in {city}",
      "Bedroom interior with upholstered bed and wardrobe",
      "Maximised storage\nCustom headboards & panelling\nIntegrated lighting\nMade-to-measure fit",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "Master bedroom\nGuest bedroom\nParents' bedroom",
      "",
      "TRUE",
      "3",
      "Hello, I am interested in Bedroom Interiors. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-004",
      "Living Room Interiors",
      "Living Room",
      "living-room",
      "Welcoming living spaces with TV units, panelling, storage and lighting design.",
      "Your living room sets the tone for the entire home. We plan furniture layout, feature walls, TV units, display and storage with a lighting plan that works day and night.",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=75",
      "",
      "Living Room Interiors in {city} | TV Units, Panelling & Storage",
      "Living room interior design in {city}: feature walls, TV units, display storage and lighting.",
      "Living Room Interior Design in {city}",
      "Living room with sofa, feature wall and warm lighting",
      "Feature walls & panelling\nBalanced furniture layout\nDisplay & concealed storage\nLayered lighting",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "TRUE",
      "4",
      "Hello, I am interested in Living Room Interiors. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-005",
      "Wardrobes",
      "Wardrobe",
      "wardrobes",
      "Sliding, hinged and walk-in wardrobes with smart internal planning.",
      "Wardrobes are planned from the inside out — hanging, drawers, lofts, lockers and accessories — then manufactured in our factory with the finish of your choice.",
      "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1600&q=75",
      "",
      "Modular Wardrobes in {city} | Sliding, Hinged & Walk-in",
      "Custom modular wardrobes in {city} — sliding, hinged and walk-in, manufactured in our own factory.",
      "Modular Wardrobes in {city}",
      "Floor-to-ceiling modular wardrobe",
      "Internal layout planned to your needs\nLoft storage\nSoft-close hardware\nMirror & glass options",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "Sliding wardrobe\nHinged wardrobe\nWalk-in wardrobe\nWardrobe with dresser",
      "",
      "TRUE",
      "5",
      "Hello, I am interested in Modular Wardrobes. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-006",
      "TV Units",
      "TV Unit",
      "tv-units",
      "Wall-mounted and floor TV units with concealed wiring and display storage.",
      "TV units designed as a feature — with concealed wiring, back panelling, display shelves and closed storage sized to your wall.",
      "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=75",
      "",
      "TV Unit Design in {city} | Modular TV Units",
      "Custom modular TV units in {city} with panelling, concealed wiring and storage.",
      "TV Unit Design in {city}",
      "Wall-mounted TV unit with panelling",
      "Concealed wiring\nFeature panelling\nOpen + closed storage",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "6",
      "Hello, I am interested in a TV Unit. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-007",
      "Pooja Units",
      "Pooja Unit",
      "pooja-units",
      "Serene pooja units and mandirs with jaali, backlighting and storage.",
      "Pooja units designed with care — CNC jaali work, backlit panels, bell provisions and storage for essentials, sized for walls, corners or dedicated rooms.",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=75",
      "",
      "",
      "Pooja Unit Design in {city} | Modular Mandir",
      "Custom pooja units in {city} with CNC jaali, backlighting and storage.",
      "Pooja Unit Design in {city}",
      "Wooden pooja unit with backlit jaali",
      "CNC jaali designs\nBacklit panels\nDrawer storage",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "7",
      "Hello, I am interested in a Pooja Unit. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-008",
      "Kids Bedroom",
      "Bedroom",
      "kids-bedroom",
      "Playful, safe and grow-with-me kids rooms with study and storage.",
      "Kids rooms that adapt as your children grow — rounded edges, study tables, bunk or storage beds and plenty of toy and book storage.",
      "https://images.unsplash.com/photo-1617104551722-3b2d51366400?auto=format&fit=crop&w=1600&q=75",
      "",
      "",
      "Kids Bedroom Interiors in {city}",
      "Kids bedroom interior design in {city} with study units, storage beds and safe finishes.",
      "Kids Bedroom Interiors in {city}",
      "Kids bedroom with study table and storage",
      "",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "8",
      "Hello, I am interested in a Kids Bedroom design. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-009",
      "Home Office",
      "Office",
      "home-office",
      "Focused work-from-home setups with ergonomic desks and storage.",
      "Home offices designed for long working hours — ergonomic desk heights, cable management, shelving and good task lighting.",
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=1600&q=75",
      "",
      "",
      "Home Office Interiors in {city}",
      "Home office and study unit design in {city}.",
      "Home Office Interiors in {city}",
      "Home office desk with shelving",
      "",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "9",
      "Hello, I am interested in a Home Office design. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-010",
      "Office Interiors",
      "Office",
      "office-interiors",
      "Workstations, cabins, reception and meeting rooms built for productivity.",
      "Office interiors that reflect your brand and help teams work better — workstations, cabins, conference rooms, reception and storage, manufactured in our factory and installed with minimal disruption.",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=75",
      "",
      "Office Interiors in {city} | Workstations, Cabins & Reception",
      "Office interior design and modular office furniture manufacturing in {city}.",
      "Office Interior Designers in {city}",
      "Modern office interior with workstations",
      "Modular workstations\nBrand-aligned design\nPhased execution",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "TRUE",
      "10",
      "Hello, I am interested in Office Interiors. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-011",
      "Commercial Interiors",
      "Commercial",
      "commercial-interiors",
      "Retail, clinics, cafés and showrooms designed to attract and convert.",
      "Commercial spaces designed around customer flow and brand — retail fixtures, counters, display systems and back-of-house storage, all manufactured in-house.",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=75",
      "",
      "",
      "Commercial Interiors in {city} | Retail, Clinics & Cafés",
      "Commercial interior design and custom fixture manufacturing in {city}.",
      "Commercial Interior Design in {city}",
      "Commercial café interior",
      "",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "11",
      "Hello, I am interested in Commercial Interiors. Please contact me for a consultation.",
      "TRUE"
    ],
    [
      "SRV-012",
      "Custom Modular Furniture",
      "Modular",
      "custom-modular-furniture",
      "Made-to-measure storage, study, utility and loft units from our factory.",
      "When standard furniture doesn't fit, we build it. Storage units, lofts, study units, shoe racks, utility cabinets and more — manufactured to your exact measurements.",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1600&q=75",
      "",
      "",
      "Custom Modular Furniture in {city} | Factory-Made",
      "Custom modular furniture manufactured in our own factory in {city}.",
      "Custom Modular Furniture in {city}",
      "Custom modular storage unit",
      "",
      "BWP / BWR grade plywood\nPre-laminated particle board & MDF (where suitable)\nHigh-pressure laminates, acrylic & PU finishes\nSoft-close hinges and channels\nBranded hardware & accessories",
      "",
      "",
      "FALSE",
      "12",
      "Hello, I am interested in Custom Modular Furniture. Please contact me for a consultation.",
      "TRUE"
    ]
  ],
  "PROJECTS": [
    [
      "PRJ-001",
      "3BHK Apartment — Warm Contemporary",
      "3bhk-warm-contemporary",
      "Visakhapatnam",
      "Full Home",
      "full-home-interiors",
      "Complete interiors for a 3BHK apartment: modular kitchen, three wardrobes, TV unit, pooja unit and storage — manufactured in our factory.",
      "2026-06",
      "1,650 sq.ft",
      "",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "TRUE",
      "1",
      "TRUE"
    ],
    [
      "PRJ-002",
      "Handleless L-Shaped Kitchen",
      "handleless-l-shaped-kitchen",
      "Visakhapatnam",
      "Kitchen",
      "modular-kitchen",
      "Handleless L-shaped kitchen with tall pantry unit and acrylic shutters.",
      "2026-05",
      "",
      "",
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1600&q=75",
      "TRUE",
      "2",
      "TRUE"
    ],
    [
      "PRJ-003",
      "Master Bedroom with Walk-in Wardrobe",
      "master-bedroom-walk-in",
      "Vizianagaram",
      "Bedroom",
      "bedroom-interiors",
      "Master bedroom with panelled headboard wall and a walk-in wardrobe.",
      "2026-04",
      "",
      "",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1600&q=75",
      "TRUE",
      "3",
      "TRUE"
    ],
    [
      "PRJ-004",
      "Living Room Feature Wall & TV Unit",
      "living-feature-wall-tv-unit",
      "Anakapalli",
      "Living Room",
      "living-room",
      "Fluted panel feature wall with floating TV unit and concealed storage.",
      "2026-03",
      "",
      "",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&w=1600&q=75",
      "TRUE",
      "4",
      "TRUE"
    ],
    [
      "PRJ-005",
      "Corporate Office — 40 Seats",
      "corporate-office-40-seats",
      "Visakhapatnam",
      "Office",
      "office-interiors",
      "Workstations, two cabins, meeting room and reception built in our factory.",
      "2026-02",
      "3,200 sq.ft",
      "",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=75\nhttps://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=75",
      "TRUE",
      "5",
      "TRUE"
    ],
    [
      "PRJ-006",
      "Sliding Wardrobe Series",
      "sliding-wardrobe-series",
      "Srikakulam",
      "Wardrobe",
      "wardrobes",
      "Three sliding wardrobes with lofts and internal drawers.",
      "2026-01",
      "",
      "",
      "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1600&q=75",
      "FALSE",
      "6",
      "TRUE"
    ],
    [
      "PRJ-007",
      "Café Fit-out",
      "cafe-fit-out",
      "Visakhapatnam",
      "Commercial",
      "commercial-interiors",
      "Service counter, back bar and seating fixtures manufactured in-house.",
      "2025-12",
      "",
      "",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=75",
      "FALSE",
      "7",
      "TRUE"
    ],
    [
      "PRJ-008",
      "Floating TV Unit",
      "floating-tv-unit",
      "Rajahmundry",
      "TV Unit",
      "tv-units",
      "Floating TV unit with backlit panel.",
      "2025-11",
      "",
      "",
      "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&w=1600&q=75",
      "FALSE",
      "8",
      "TRUE"
    ]
  ],
  "GALLERY": [
    [
      "IMG-001",
      "PRJ-002",
      "Kitchen",
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=75",
      "L-shaped kitchen",
      "",
      "1",
      "TRUE"
    ],
    [
      "IMG-002",
      "",
      "Kitchen",
      "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1600&q=75",
      "Island kitchen",
      "",
      "2",
      "TRUE"
    ],
    [
      "IMG-003",
      "PRJ-003",
      "Bedroom",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=75",
      "Master bedroom",
      "",
      "3",
      "TRUE"
    ],
    [
      "IMG-004",
      "",
      "Living Room",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=75",
      "Open living & dining",
      "",
      "4",
      "TRUE"
    ],
    [
      "IMG-005",
      "PRJ-003",
      "Wardrobe",
      "https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&w=1600&q=75",
      "Walk-in wardrobe",
      "",
      "5",
      "TRUE"
    ],
    [
      "IMG-006",
      "PRJ-008",
      "TV Unit",
      "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&w=1600&q=75",
      "Floating TV unit",
      "",
      "6",
      "TRUE"
    ],
    [
      "IMG-007",
      "PRJ-001",
      "Full Home",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=75",
      "3BHK living room",
      "",
      "7",
      "TRUE"
    ],
    [
      "IMG-008",
      "PRJ-005",
      "Office",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=75",
      "Meeting room",
      "",
      "8",
      "TRUE"
    ],
    [
      "IMG-009",
      "PRJ-007",
      "Commercial",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1600&q=75",
      "Café counter",
      "",
      "9",
      "TRUE"
    ],
    [
      "IMG-010",
      "",
      "Factory",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1600&q=75",
      "Panel processing",
      "",
      "10",
      "TRUE"
    ],
    [
      "IMG-011",
      "",
      "Factory",
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=75",
      "Assembly line",
      "",
      "11",
      "TRUE"
    ],
    [
      "IMG-012",
      "",
      "Factory",
      "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1600&q=75",
      "Machinery",
      "",
      "12",
      "TRUE"
    ]
  ],
  "BEFORE_AFTER": [
    [
      "BA-001",
      "Kitchen Renovation",
      "A dated kitchen transformed into a bright, storage-rich modular kitchen.",
      "Visakhapatnam",
      "Kitchen",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=75",
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=75",
      "1",
      "TRUE"
    ]
  ],
  "TESTIMONIALS": [
    [
      "TST-001",
      "Sample Customer",
      "Visakhapatnam",
      "Full Home Interiors",
      "Replace this with a real, approved customer review from the TESTIMONIALS sheet and set Active to TRUE.",
      "5",
      "",
      "1",
      "FALSE"
    ]
  ],
  "FACTORY": [
    [
      "FP-01",
      "process",
      "Customer Requirement",
      "We understand your lifestyle, needs and budget.",
      "",
      "1",
      "TRUE"
    ],
    [
      "FP-02",
      "process",
      "Site Measurement",
      "Precise on-site measurements by our team.",
      "",
      "2",
      "TRUE"
    ],
    [
      "FP-03",
      "process",
      "2D Planning",
      "Space planning and furniture layout.",
      "",
      "3",
      "TRUE"
    ],
    [
      "FP-04",
      "process",
      "3D Design",
      "Photo-realistic 3D views of your space.",
      "",
      "4",
      "TRUE"
    ],
    [
      "FP-05",
      "process",
      "Design Approval",
      "You review, refine and approve every detail.",
      "",
      "5",
      "TRUE"
    ],
    [
      "FP-06",
      "process",
      "Material Selection",
      "Boards, laminates, finishes and hardware finalised.",
      "",
      "6",
      "TRUE"
    ],
    [
      "FP-07",
      "process",
      "Production Planning",
      "Cutting lists and production schedule prepared.",
      "",
      "7",
      "TRUE"
    ],
    [
      "FP-08",
      "process",
      "Panel Cutting",
      "Accurate panel sizing on precision saws.",
      "",
      "8",
      "TRUE"
    ],
    [
      "FP-09",
      "process",
      "Edge Banding",
      "Edges sealed for durability and a clean finish.",
      "",
      "9",
      "TRUE"
    ],
    [
      "FP-10",
      "process",
      "Drilling / CNC",
      "Hardware drilling and CNC work where applicable.",
      "",
      "10",
      "TRUE"
    ],
    [
      "FP-11",
      "process",
      "Assembly",
      "Units assembled and dry-fitted in the factory.",
      "",
      "11",
      "TRUE"
    ],
    [
      "FP-12",
      "process",
      "Quality Inspection",
      "Dimensions, finish and hardware checked.",
      "",
      "12",
      "TRUE"
    ],
    [
      "FP-13",
      "process",
      "Packing",
      "Protective packing for safe transport.",
      "",
      "13",
      "TRUE"
    ],
    [
      "FP-14",
      "process",
      "Delivery",
      "Scheduled delivery to your site.",
      "",
      "14",
      "TRUE"
    ],
    [
      "FP-15",
      "process",
      "Installation",
      "Installed by our trained installation team.",
      "",
      "15",
      "TRUE"
    ],
    [
      "FC-01",
      "capability",
      "Cutting",
      "Precision panel cutting for accurate sizes.",
      "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1600&q=75",
      "1",
      "TRUE"
    ],
    [
      "FC-02",
      "capability",
      "Edge Banding",
      "Clean, sealed edges on every panel.",
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=75",
      "2",
      "TRUE"
    ],
    [
      "FC-03",
      "capability",
      "Drilling & CNC",
      "Hardware drilling and CNC work where applicable.",
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1600&q=75",
      "3",
      "TRUE"
    ],
    [
      "FC-04",
      "capability",
      "Assembly",
      "Units assembled and checked before dispatch.",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1600&q=75",
      "4",
      "TRUE"
    ],
    [
      "FC-05",
      "capability",
      "Quality Checking",
      "Dimensional and finish inspection.",
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1600&q=75",
      "5",
      "TRUE"
    ],
    [
      "FC-06",
      "capability",
      "Packing",
      "Protective packing for safe delivery.",
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1600&q=75",
      "6",
      "TRUE"
    ]
  ],
  "CONTENT_CALENDAR": [
    [
      "Monday",
      "Modular Kitchen",
      "modular-kitchen",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Tuesday",
      "Bedroom Interior",
      "bedroom-interiors",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Wednesday",
      "Factory / Manufacturing",
      "",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Thursday",
      "Before & After",
      "",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Friday",
      "Completed Project",
      "",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Saturday",
      "Interior Tip",
      "",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ],
    [
      "Sunday",
      "Consultation / CTA",
      "",
      "Image",
      "Instagram",
      "18:30",
      "TRUE"
    ]
  ],
  "CAMPAIGNS": [
    [
      "CMP-001",
      "Modular Kitchen — Instagram",
      "Instagram",
      "2026-09-01",
      "2026-09-30",
      "/interiors/modular-kitchen",
      "instagram",
      "social",
      "kitchen_sep26",
      "",
      "0",
      "0",
      "0",
      "0",
      "Active"
    ]
  ]
};
